backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "tournaments"
    label: "Tournaments"
    label_singular: "Tournament"
    files:
      - file: "content/tournaments.json"
        label: "Tournaments List"
        name: "tournamentslist"
        fields:
          - label: "Tournaments"
            name: "tournaments"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Link", name: "link", widget: "string" }
