backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "tournaments"
    label: "Tournaments"
    folder: "content"
    create: true
    slug: "tournaments"
    format: "json"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
