backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Tournaments"
    name: "tournaments"
    files:
      - label: "Tournaments Data"
        name: "tournamentsdata"
        file: "content/tournaments.json"
        format: "json"
        fields:
          - label: "Tournaments"
            name: "tournaments"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Link", name: "link", widget: "string" }
